# Generated by Django 4.2 on 2023-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_post_image_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/PICS/logo.png', upload_to='static/blog_images/'),
        ),
    ]
